code_extensions:
  - 2gua.rainbow-brackets
  - aaron-bond.better-comments
  - abusaidm.html-snippets
  - amazonwebservices.aws-toolkit-vscode
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - demijollamaxime.bulma
  - DigitalBrainstem.javascript-ejs-support
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - ecmel.vscode-html-css
  - formulahendry.auto-close-tag
  - Kelvin.vscode-sshfs
  - marp-team.marp-vscode
  - mechatroner.rainbow-csv
  - mkaufman.HTMLHint
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-ssh-explorer
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode.Go
  - octref.vetur
  - oderwat.indent-rainbow
  - pkosta2005.heroku-command
  - rebornix.ruby
  - redhat.vscode-yaml
  - rust-lang.rust
  - satokaz.vscode-bs-ctrlchar-remover
  - shd101wyy.markdown-preview-enhanced
  - sysoev.language-stylus
  - techer.open-in-browser
  - vadimcn.vscode-lldb
  - vscode-icons-team.vscode-icons
  - vscodevim.vim
  - vscoss.vscode-ansible
  - wingrunr21.vscode-ruby
  - xabikos.JavaScriptSnippets
  - yzhang.markdown-all-in-one
  - Zignd.html-css-class-completion
