extensions:
  - 2gua.rainbow-brackets
  - abusaidm.html-snippets
  - amazonwebservices.aws-toolkit-vscode
  - aws-amplify.aws-amplify-vscode
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - ecmel.vscode-html-css
  - formulahendry.auto-close-tag
  - formulahendry.code-runner
  - Kelvin.vscode-sshfs
  - mechatroner.rainbow-csv
  - mkaufman.HTMLHint
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-ssh-explorer
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode.cpptools
  - oderwat.indent-rainbow
  - pkosta2005.heroku-command
  - redhat.vscode-yaml
  - satokaz.vscode-bs-ctrlchar-remover
  - techer.open-in-browser
  - vadimcn.vscode-lldb
  - vsciot-vscode.vscode-arduino
  - vscode-icons-team.vscode-icons
  - vscodevim.vim
  - vscoss.vscode-ansible
  - yzhang.markdown-all-in-one
  - Zignd.html-css-class-completion

